### ISSUE TITLE
"JSX element type 'SvelteTable' does not have any construct or call signatures."

### ISSUE THREAD

**Issue by felluksch** [hurtigruten/svelte-table#29]
Hi, 
I get the above error trying to use SvelteTable in TypeScript.
`export class SvelteTable extends SvelteComponentTyped<SvelteTableProps> {}` in `src/index.d.ts` might resolve this issue? Svelte introduced `SvelteComponentTyped`with version 3.31. Please let me know if you need more information to reproduce.

**Comment by neonwarp** [comment]
Hi! Sorry for the late reply. Can you please provide more details about TypeScript and Svelte versions? We are using this without an issue on TS 4.5.5 and Svelte 3.46.2. I'll look into `SvelteComponentTyped`, thanks for the tip!

**Comment by bartektelec** [comment]
I think we will need more context in order to fix this as this has not been reported by anyone else I assume the problem is not with the library itself.
This issue has been stale with not enough information provided.

If this is still an issue, please post a code snippet that will help us reproduce the issue, ideally together with your project's Svelte/Node/TypeScript versions
